// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqudukheyahowyukigxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxdWR1a2hleWFob3d5dWtpZ3h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjQzODksImV4cCI6MjA3MDA0MDM4OX0.BhgP1-9Pj0GQpMh0j43hRbiqtW9f-7RD5_FCre5qeeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});